apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: spring
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring
        tier: db  
    spec:
      containers:
      - image: Osamazx/react-spring-rest-db
        name: db
        ports:
        - containerPort: 1521
          name: db
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: db-pv-claim